compatibility_date = "2024-10-05"
main = "src/sv/index.ts"
name = "cottonwind-sv"

[triggers]
crons = ["0 19 * * *"]

[vars]
ACCOUNT_ID = "95737cecb3c443e0b8979d9679110507"
PROJECT_NAME = "cottonwind-page"
EXPIRATION_DAYS = 1
