compatibility_date = "2024-08-29"
main = "src/api/index.ts"
name = "cottonwind-api"

[triggers]
crons = ["0 19 * * *"]

[vars]
ORIGIN = "https://cottonwind.com"
VERSION = "1.1.0"

AUTHOR_ACCOUNT = "kouwtkz"
TITLE = "こっとんうぃんどのAPI"

CORS_ORIGIN = [
  "https://cottonwind.com",
  "https://cottonwind.pages.dev",
  "http://localhost:51730",
  "http://127.0.0.1:51730",
  "http://192.168.1.30:51730",
]
ORIGIN_HOST = "cottonwind.com"
PAGES_DEV_ORIGIN = "https://cottonwind.pages.dev"

API_ORIGIN = "https://api.cottonwind.com"
API_WORKERS_ORIGIN = "https://cottonwind-api.kouwtkz.workers.dev"

MEDIA_ORIGIN = "https://media.cottonwind.com"
MEDIA_WORKERS_ORIGIN = "https://cottonwind-r2.kouwtkz.workers.dev"
MEDIA_LOCAL_ORIGIN = "http://localhost:51732"

API_LOCAL_ORIGIN = "http://localhost:51731"
LOCAL_ORIGIN = "http://localhost:51730"

LIFE_CHECK_URL = "https://cottonwind.com/life/check"
# LIFE_CHECK_URL = "http://localhost:51730/life/check"

FEED_FROM = "https://note.com/kouwtkz/rss"

THUMBNAIL_SIZE = 340

[[kv_namespaces]]
binding = "KV"
id = "c4d890a161dc4d8abc299dd09d8b3165"
preview_id = "baf0b24ce5014aa4b8fcd5a6774bc026"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cottonwind-bucket"

[[d1_databases]]
binding = "DB"
database_id = "8d8bef89-42a4-436d-991a-ebdbd3b252a5"
database_name = "cottonwind-db"

# [ai]
# binding = "AI"
