name = "cottonwind-api"

compatibility_date = "2024-08-29"
main = "src/api/index.ts"

[vars]
ORIGIN = "https://cottonwind.com"

TITLE = "こっとんうぃんど"
AUTHOR_ACCOUNT = "kouwtkz"

CORS_ORIGIN = [
  "http://localhost:51730",
  "https://cottonwind.com",
]
ORIGIN_HOST = "cottonwind.com"
PAGES_DEV_ORIGIN = "https://cottonwind.pages.dev"

API_ORIGIN = "https://api.cottonwind.com"
API_WORKERS_ORIGIN = "https://cottonwind-api.kouwtkz.workers.dev"

API_LOCAL_ORIGIN = "http://localhost:51731"
LOCAL_ORIGIN = "http://localhost:51730"

[[kv_namespaces]]
binding = "KV"
id = "c4d890a161dc4d8abc299dd09d8b3165"
preview_id = "baf0b24ce5014aa4b8fcd5a6774bc026"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
