import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("gallery", "routes/gallery.tsx"),
  route("gallery/:group", "routes/galleryGroup.tsx"),
  route("character", "routes/characterList.tsx"),
  route("character/:charaName", "routes/character.tsx"),
  route("sound", "routes/sound.tsx"),
  route("links", "routes/links.tsx"),
  route("works", "routes/works.tsx"),
  route("about", "routes/about.tsx"),
  route("blog", "routes/blog.tsx"),
  route("schedule", "routes/schedule.tsx"),
  route("setting", "routes/setting.tsx"),
  route("admin", "routes/admin/admin.tsx"),
  route("login", "routes/session/login.tsx"),
  route("logout", "routes/session/logout.tsx"),
  route("media/*", "./media.ts"),
  route("api", "routes/api/index.ts", [
    route("data/:param", "routes/api/data.ts"),
    route("image/:action", "routes/api/image.ts"),
    route("character/:action", "routes/api/character.ts"),
    route("blog/:action", "routes/api/blog.ts"),
    route("sound/:action", "routes/api/sound.ts"),
    route("sound/album/:action", "routes/api/soundAlbum.ts"),
    route("file/:action", "routes/api/file.ts"),
    route("links/:action", "routes/api/links.ts"),
    route("links/fav/:action", "routes/api/links-fav.ts"),
    route("like/:action", "routes/api/like.ts"),
    route("kvdb/:action", "routes/api/KeyValueDB.ts"),
    route("discord/:action", "routes/api/discord.ts"),
  ]),
] satisfies RouteConfig;
